---
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: '09:00'
    timezone: Europe/Madrid
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - python
  assignees:
  - javiyt
  reviewers:
  - javiyt
  groups:
    python-minor-patch-updates:
      applies-to: version-updates
      patterns:
      - "*"
      update-types:
      - minor
      - patch
    python-major-updates:
      applies-to: version-updates
      patterns:
      - "*"
      update-types:
      - major
    python-security-updates:
      applies-to: security-updates
      patterns:
      - "*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: '09:00'
    timezone: Europe/Madrid
  open-pull-requests-limit: 5
  labels:
  - dependencies
  - github-actions
  assignees:
  - javiyt
  reviewers:
  - javiyt
  groups:
    github-actions-minor-patch-updates:
      applies-to: version-updates
      patterns:
      - "*"
      update-types:
      - minor
      - patch
    github-actions-major-updates:
      applies-to: version-updates
      patterns:
      - "*"
      update-types:
      - major
    github-actions-security-updates:
      applies-to: security-updates
      patterns:
      - "*"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    time: '09:00'
    timezone: Europe/Madrid
  open-pull-requests-limit: 3
  labels:
  - dependencies
  - docker
  assignees:
  - javiyt
  reviewers:
  - javiyt
  groups:
    docker-minor-patch-updates:
      applies-to: version-updates
      patterns:
      - "*"
      update-types:
      - minor
      - patch
    docker-major-updates:
      applies-to: version-updates
      patterns:
      - "*"
      update-types:
      - major
    docker-security-updates:
      applies-to: security-updates
      patterns:
      - "*"
